global:
  checkNewVersion: false

entryPoints:
  public:
    address: ":8080"
  internal:
    address: ":8081"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO
